workflows:
  ios-build:
    name: Wydatki iOS
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      xcode: 16.4
      vars:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Make Gradle executable
        script: |
          chmod +x ./gradlew

      - name: Show environment
        script: |
          java -version
          xcodebuild -version
          pod --version

      - name: Generate ComposeApp CocoaPods framework
        script: |
          ./gradlew :composeApp:podInstall

      - name: Install CocoaPods
        script: |
          cd iosApp
          pod install --repo-update

      - name: Build iOS
        script: |
          xcodebuild \
            -workspace iosApp/iosApp.xcworkspace \
            -scheme iosApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            EXCLUDED_ARCHS=x86_64 \
            build

    artifacts:
      - build/ios/Debug-iphonesimulator/*.app
